// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/portfolio/:slug": {
    params: {
      "slug": string;
    };
  };
  "/portfolio/category/:category": {
    params: {
      "category": string;
    };
  };
  "/advancing-skills": {
    params: {};
  };
  "/plugins": {
    params: {};
  };
  "/plugins/:slug": {
    params: {
      "slug": string;
    };
  };
  "/plugins/:slug/documentation": {
    params: {
      "slug": string;
    };
  };
  "/plugins/:slug/api-reference": {
    params: {
      "slug": string;
    };
  };
  "/.well-known/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/about" | "/portfolio" | "/portfolio/:slug" | "/portfolio/category/:category" | "/advancing-skills" | "/plugins" | "/plugins/:slug" | "/plugins/:slug/documentation" | "/plugins/:slug/api-reference" | "/.well-known/*" | "/*";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.jsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/portfolio.jsx": {
    id: "p-list";
    page: "/portfolio";
  } | {
    id: "p-cat";
    page: "/portfolio/category/:category";
  } | {
    id: "p-skills";
    page: "/advancing-skills";
  };
  "routes/portfolio.$slug.jsx": {
    id: "routes/portfolio.$slug";
    page: "/portfolio/:slug";
  };
  "routes/plugins.jsx": {
    id: "routes/plugins";
    page: "/plugins";
  };
  "routes/plugins/slug.layout.jsx": {
    id: "routes/plugins/slug.layout";
    page: "/plugins/:slug" | "/plugins/:slug/documentation" | "/plugins/:slug/api-reference";
  };
  "routes/plugins/slug.index.jsx": {
    id: "routes/plugins/slug.index";
    page: "/plugins/:slug";
  };
  "routes/plugins/slug.documentation.jsx": {
    id: "routes/plugins/slug.documentation";
    page: "/plugins/:slug/documentation";
  };
  "routes/plugins/slug.api-reference.jsx": {
    id: "routes/plugins/slug.api-reference";
    page: "/plugins/:slug/api-reference";
  };
  "routes/silence.jsx": {
    id: "routes/silence";
    page: "/.well-known/*";
  };
  "routes/$.jsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/about": typeof import("./app/routes/about.jsx");
  "p-list": typeof import("./app/routes/portfolio.jsx");
  "routes/portfolio.$slug": typeof import("./app/routes/portfolio.$slug.jsx");
  "p-cat": typeof import("./app/routes/portfolio.jsx");
  "p-skills": typeof import("./app/routes/portfolio.jsx");
  "routes/plugins": typeof import("./app/routes/plugins.jsx");
  "routes/plugins/slug.layout": typeof import("./app/routes/plugins/slug.layout.jsx");
  "routes/plugins/slug.index": typeof import("./app/routes/plugins/slug.index.jsx");
  "routes/plugins/slug.documentation": typeof import("./app/routes/plugins/slug.documentation.jsx");
  "routes/plugins/slug.api-reference": typeof import("./app/routes/plugins/slug.api-reference.jsx");
  "routes/silence": typeof import("./app/routes/silence.jsx");
  "routes/$": typeof import("./app/routes/$.jsx");
};