import { Link, useOutletContext } from "react-router";
import { motion } from "motion/react";
import {
  Code2,
  ChevronRight,
  Mic2,
  FileText,
  Database,
  Radio,
  Webhook,
  Globe,
} from "lucide-react";

// ─────────────────────────────────────────────
// Dados extraídos do DOCUMENTATION.md
// ─────────────────────────────────────────────

const phpMethods = [
  {
    id: "generate-audio",
    icon: <Mic2 />,
    title: "Generate Audio",
    class: "VoxAiAu_API",
    method: "generate_tts_audio",
    description:
      "Sends the post content to the OpenAI API and generates an MP3 file, saving it to the server.",
    usage: `$api = VoxAiAu_API::get_instance();
$audio_url = $api->generate_tts_audio( $post_id, $voice, $tts_model );`,
    params: [
      { name: "$post_id",   type: "int",    req: true,  desc: "WordPress post ID." },
      { name: "$voice",     type: "string", req: false, desc: "TTS Voice: alloy | echo | fable | onyx | nova | shimmer. Default: alloy." },
      { name: "$tts_model", type: "string", req: false, desc: "Audio model: tts-1 or tts-1-hd. Default: value from settings." },
    ],
    response: `{
  "success":   true,
  "audio_url": "https://yoursite.com/wp-content/uploads/voxai/2026/04/my-post-2026-04-27-14-32-00.mp3",
  "has_audio": true
}`,
  },
  {
    id: "generate-summary",
    icon: <FileText />,
    title: "Generate Summary",
    class: "VoxAiAu_API",
    method: "generate_summary",
    description:
      "Sends the content to the GPT-4o Mini model and returns a TL;DR summary.",
    usage: `$api = VoxAiAu_API::get_instance();
$summary = $api->generate_summary( $content, $options );`,
    params: [
      { name: "$content",   type: "string", req: true,  desc: "WordPress post content." },
      { name: "$max_words", type: "int",    req: false, desc: "Maximum number of words for the summary. Default: 90." },
      { name: "$title",     type: "string", req: false, desc: "Post title for additional prompt context." },
    ],
    response: `{
  "success":     true,
  "summary":     "VoxAI transforms posts into audio...",
  "has_summary": true
}`,
  },
  {
    id: "cache-status",
    icon: <Database />,
    title: "Post Status",
    class: "VoxAiAu_Cache",
    method: "get_audio / get_summary",
    description:
      "Checks if the post already has a generated audio and/or summary.",
    usage: `$cache = VoxAiAu_Cache::get_instance();
$has_audio   = $cache->get_audio( $post_id );   // string|false
$has_summary = $cache->get_summary( $post_id ); // string|false`,
    params: [
      { name: "$post_id", type: "int", req: true, desc: "WordPress post ID." },
    ],
    response: `{
  "has_audio":   true,
  "audio_url":   "https://yoursite.com/wp-content/uploads/voxai/2026/04/my-post.mp3",
  "has_summary": true
}`,
  },
];

const voices = [
  { id: "alloy",   label: "Alloy",   gender: "Neu" },
  { id: "echo",    label: "Echo",    gender: "M"   },
  { id: "fable",   label: "Fable",   gender: "F"   },
  { id: "onyx",    label: "Onyx",    gender: "M"   },
  { id: "nova",    label: "Nova",    gender: "F"   },
  { id: "shimmer", label: "Shimmer", gender: "F"   },
];

const filters = [
  { hook: "voxaiau_summary_model",         type: "string", desc: "Overrides the GPT model used to generate summaries." },
  { hook: "voxaiau_summary_system_prompt", type: "string", desc: "Overrides the system prompt sent to GPT. Receives $prompt and $content." },
  { hook: "voxaiau_tts_model",             type: "string", desc: "Overrides the TTS model (tts-1 or tts-1-hd)." },
  { hook: "voxaiau_tts_voice",             type: "string", desc: "Overrides the default TTS voice." },
  { hook: "voxaiau_tts_custom_intro_text", type: "string", desc: "Injects a fixed intro text before the narrated content. Receives $text and $post." },
];

const actions = [
  {
    hook: "voxaiau_audio_generated",
    params: "$post_id, $audio_url",
    desc: "Fired immediately after the MP3 is saved on the server. Ideal for asynchronous processing.",
  },
];

const restEndpoints = [
  {
    id: "rest-summary",
    method: "GET",
    path: "/wp-json/voxai/v1/summary/{id}",
    description:
      "Returns the summary of a post. If the summary doesn't exist yet, it is generated and cached automatically.",
    auth: "Public for posts with publish status. Password-protected or private posts require authentication.",
    params: [
      { name: "id", type: "int", desc: "WordPress post ID." },
    ],
    response: `{
  "success": true,
  "summary": "<p>Smart summary generated by VoxAI...</p>",
  "source":  "cache"
}`,
    sourceNote: 'The source field can be "cache" (summary already existed) or "generated" (generated just now).',
    errorResponse: `{
  "code":    "post_not_found",
  "message": "Post not found.",
  "data":    { "status": 404 }
}`,
    errorCodes: [
      { code: "post_not_found", status: "404",     desc: "Post not found." },
      { code: "rest_forbidden", status: "401/403", desc: "Password-protected post or user without permission." },
      { code: "empty_content",  status: "404",     desc: "Post with no content to summarize." },
      { code: "missing_api_key",status: "500",     desc: "OpenAI API Key not configured." },
      { code: "api_rate_limit", status: "429",     desc: "OpenAI API rate limit reached." },
      { code: "api_unauthorized",status: "401",    desc: "Invalid or revoked API Key." },
    ],
  },
];

const methodColor = { GET: "#699cff", POST: "#ba9eff" };

const navLinks = [
  { id: "generate-audio",   label: "generate_tts_audio()" },
  { id: "generate-summary", label: "generate_summary()" },
  { id: "cache-status",     label: "VoxAiAu_Cache" },
  { id: "voices",           label: "Available Voices" },
  { id: "hooks",            label: "Filters & Actions" },
  { id: "rest-summary",     label: "REST API" },
];

export default function ApiReference() {
  const { project, slug } = useOutletContext();

  return (
    <div className="vox-subpage">
      {/* ── Page header */}
      <div className="vox-subpage__hero vox-section--dark">
        <div className="vox-container">
          <div className="vox-breadcrumb">
            <Link to={`/plugins/${slug}`}>{project.title}</Link>
            <ChevronRight style={{ width: 14, height: 14, opacity: 0.4 }} />
            <span>API Reference</span>
          </div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <div className="vox-subpage__icon">
              <Code2 style={{ width: 28, height: 28, color: "#699cff" }} />
            </div>
            <h1 className="vox-subpage__title">API Reference</h1>
            <p className="vox-subpage__desc">
              PHP functions available to integrate{" "}
              <strong>{project.title}</strong> with themes, plugins, and custom hooks.
            </p>
          </motion.div>
        </div>
      </div>

      {/* ── Content */}
      <div className="vox-container vox-subpage__body">
        <aside className="vox-subpage__sidebar">
          <nav className="vox-doc-nav">
            <p className="vox-doc-nav__title">On this page</p>
            {navLinks.map((l) => (
              <a 
                key={l.id} 
                href={`#${l.id}`} 
                className="vox-doc-nav__link"
                onClick={(e) => {
                  e.preventDefault();
                  const element = document.getElementById(l.id);
                  if (element) {
                    const y = element.getBoundingClientRect().top + window.scrollY - 90;
                    window.scrollTo({ top: y, behavior: 'smooth' });
                    window.history.pushState(null, '', `#${l.id}`);
                  }
                }}
              >
                {l.label}
              </a>
            ))}
          </nav>
        </aside>

        <div className="vox-subpage__content">

          {/* ── PHP Methods */}
          {phpMethods.map((ep, idx) => (
            <motion.section
              key={ep.id}
              id={ep.id}
              className="vox-doc-section vox-api-section"
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: idx * 0.05 }}
            >
              {/* Class + method badge */}
              <div className="vox-api-section__path">
                <span className="vox-api-badge" style={{ background: "rgba(105,156,255,.15)", color: "#699cff" }}>
                  PHP
                </span>
                <code className="vox-api-path-code">
                  {ep.class}::{ep.method}()
                </code>
              </div>

              <div className="vox-doc-section__header">
                <span className="vox-doc-section__icon">{ep.icon}</span>
                <h2 className="vox-doc-section__title">{ep.title}</h2>
              </div>

              <p className="vox-doc-section__desc">{ep.description}</p>

              {/* Usage */}
              <p className="vox-doc-section__subtitle">Usage</p>
              <div className="vox-api-response">
                <div className="code-block">
                  <pre className="vox-api-pre">{ep.usage}</pre>
                </div>
              </div>

              {/* Parameters */}
              <p className="vox-doc-section__subtitle">Parameters</p>
              <div className="vox-api-params">
                <table className="vox-api-table">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Type</th>
                      <th>Req.</th>
                      <th>Description</th>
                    </tr>
                  </thead>
                  <tbody>
                    {ep.params.map((p) => (
                      <tr key={p.name}>
                        <td><code className="vox-api-code">{p.name}</code></td>
                        <td><span className="vox-api-type">{p.type}</span></td>
                        <td>
                          {p.req
                            ? <span className="vox-api-req">Yes</span>
                            : <span className="vox-api-opt">No</span>}
                        </td>
                        <td>{p.desc}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Response */}
              <p className="vox-doc-section__subtitle">Response (JSON)</p>
              <div className="vox-api-response">
                <div className="code-block">
                  <pre className="vox-api-pre">{ep.response}</pre>
                </div>
              </div>
            </motion.section>
          ))}

          {/* ── Vozes Disponíveis */}
          <motion.section
            id="voices"
            className="vox-doc-section vox-api-section"
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.15 }}
          >
            <div className="vox-api-section__path">
              <span className="vox-api-badge" style={{ background: "rgba(105,156,255,.15)", color: "#699cff" }}>
                PHP
              </span>
              <code className="vox-api-path-code">available voices</code>
            </div>

            <div className="vox-doc-section__header">
              <span className="vox-doc-section__icon"><Radio /></span>
              <h2 className="vox-doc-section__title">Available Voices</h2>
            </div>
            <p className="vox-doc-section__desc">
              Lists all available TTS voices. Pass the <code className="vox-api-code">id</code> to the{" "}
              <code className="vox-api-code">$voice</code> parameter in <code className="vox-api-code">generate_tts_audio()</code>.
            </p>

            <div className="vox-api-params">
              <table className="vox-api-table">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Label</th>
                    <th>Gender</th>
                  </tr>
                </thead>
                <tbody>
                  {voices.map((v) => (
                    <tr key={v.id}>
                      <td><code className="vox-api-code">{v.id}</code></td>
                      <td>{v.label}</td>
                      <td><span className="vox-api-type">{v.gender}</span></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <p className="vox-doc-section__subtitle">Response (JSON)</p>
            <div className="vox-api-response">
              <div className="code-block">
                <pre className="vox-api-pre">{`{
  "voices": [
    { "id": "alloy",   "label": "Alloy",   "gender": "Neu" },
    { "id": "echo",    "label": "Echo",    "gender": "M"   },
    { "id": "fable",   "label": "Fable",   "gender": "F"   },
    { "id": "onyx",    "label": "Onyx",    "gender": "M"   },
    { "id": "nova",    "label": "Nova",    "gender": "F"   },
    { "id": "shimmer", "label": "Shimmer", "gender": "F"   }
  ]
}`}</pre>
              </div>
            </div>
          </motion.section>

          {/* ── Filtros & Actions */}
          <motion.section
            id="hooks"
            className="vox-doc-section"
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2 }}
          >
            <div className="vox-doc-section__header">
              <span className="vox-doc-section__icon"><Webhook /></span>
              <h2 className="vox-doc-section__title">Filters & Actions</h2>
            </div>
            <p className="vox-doc-section__desc">
              VoxAI exposes filters and actions for developers to customize the behavior without modifying the core plugin.
            </p>

            {/* Filters table */}
            <p className="vox-doc-section__subtitle">Filters</p>
            <div className="vox-api-params">
              <table className="vox-api-table">
                <thead>
                  <tr>
                    <th>Filter</th>
                    <th>Type</th>
                    <th>Description</th>
                  </tr>
                </thead>
                <tbody>
                  {filters.map((f) => (
                    <tr key={f.hook}>
                      <td><code className="vox-api-code">{f.hook}</code></td>
                      <td><span className="vox-api-type">{f.type}</span></td>
                      <td>{f.desc}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Filter examples */}
            <p className="vox-doc-section__subtitle">Example — Change summary model</p>
            <div className="vox-api-response">
              <div className="code-block">
                <pre className="vox-api-pre">{`add_filter( 'voxaiau_summary_model', function( $model ) {
    return 'gpt-4o'; // Use GPT-4o instead of GPT-4o Mini
});`}</pre>
              </div>
            </div>

            <p className="vox-doc-section__subtitle">Example — Add custom intro to audio</p>
            <div className="vox-api-response">
              <div className="code-block">
                <pre className="vox-api-pre">{`add_filter( 'voxaiau_tts_custom_intro_text', function( $text, $post ) {
    return 'Welcome to My Site. You are listening to: ' . $post->post_title . '.';
}, 10, 2 );`}</pre>
              </div>
            </div>

            {/* Actions table */}
            <p className="vox-doc-section__subtitle">Actions</p>
            <div className="vox-api-params">
              <table className="vox-api-table">
                <thead>
                  <tr>
                    <th>Action</th>
                    <th>Parameters</th>
                    <th>Description</th>
                  </tr>
                </thead>
                <tbody>
                  {actions.map((a) => (
                    <tr key={a.hook}>
                      <td><code className="vox-api-code">{a.hook}</code></td>
                      <td><span className="vox-api-type">{a.params}</span></td>
                      <td>{a.desc}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <p className="vox-doc-section__subtitle">Example — Process audio after generation</p>
            <div className="vox-api-response">
              <div className="code-block">
                <pre className="vox-api-pre">{`add_action( 'voxaiau_audio_generated', function( $post_id, $audio_url ) {
    // Enfileirar tarefa de transcrição, notificação, etc.
}, 10, 2 );`}</pre>
              </div>
            </div>
          </motion.section>

          {/* ── REST API */}
          {restEndpoints.map((ep, idx) => (
            <motion.section
              key={ep.id}
              id={ep.id}
              className="vox-doc-section vox-api-section"
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: (idx + 5) * 0.05 }}
            >
              <div className="vox-api-section__path">
                <span
                  className="vox-api-badge"
                  style={{
                    background: `${methodColor[ep.method]}20`,
                    color: methodColor[ep.method],
                  }}
                >
                  {ep.method}
                </span>
                <code className="vox-api-path-code">{ep.path}</code>
              </div>

              <div className="vox-doc-section__header">
                <span className="vox-doc-section__icon"><Globe /></span>
                <h2 className="vox-doc-section__title">REST API — Summary</h2>
              </div>

              <p className="vox-doc-section__desc">{ep.description}</p>

              <div className="vox-doc-tip">
                <strong>Authentication:</strong> {ep.auth}
              </div>

              {/* URL params */}
              <p className="vox-doc-section__subtitle">URL Parameters</p>
              <div className="vox-api-params">
                <table className="vox-api-table">
                  <thead>
                    <tr>
                      <th>Parameter</th>
                      <th>Type</th>
                      <th>Description</th>
                    </tr>
                  </thead>
                  <tbody>
                    {ep.params.map((p) => (
                      <tr key={p.name}>
                        <td><code className="vox-api-code">{p.name}</code></td>
                        <td><span className="vox-api-type">{p.type}</span></td>
                        <td>{p.desc}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Success response */}
              <p className="vox-doc-section__subtitle">Success Response (200)</p>
              <div className="vox-api-response">
                <div className="code-block">
                  <pre className="vox-api-pre">{ep.response}</pre>
                </div>
              </div>
              {ep.sourceNote && (
                <div className="vox-doc-tip" style={{ marginTop: ".75rem" }}>
                  {ep.sourceNote}
                </div>
              )}

              {/* Error response */}
              <p className="vox-doc-section__subtitle">Error Response</p>
              <div className="vox-api-response">
                <div className="code-block">
                  <pre className="vox-api-pre">{ep.errorResponse}</pre>
                </div>
              </div>

              {/* Error codes */}
              <p className="vox-doc-section__subtitle">Common Error Codes</p>
              <div className="vox-api-params">
                <table className="vox-api-table">
                  <thead>
                    <tr>
                      <th>Code</th>
                      <th>HTTP Status</th>
                      <th>Description</th>
                    </tr>
                  </thead>
                  <tbody>
                    {ep.errorCodes.map((e) => (
                      <tr key={e.code}>
                        <td><code className="vox-api-code">{e.code}</code></td>
                        <td><span className="vox-api-type">{e.status}</span></td>
                        <td>{e.desc}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </motion.section>
          ))}

        </div>
      </div>
    </div>
  );
}
